Repository jellyfishing2346/Love-Language-GPT, pull requests merged in 2025-04, with the labels that each got.

#14 Implement message routes with OpenAI translation
  backend/package-lock.json
  backend/src/database.ts
  backend/src/elysiajs__cors.d.ts
  backend/src/modules/ai/index.ts
  backend/src/modules/ai/translation.ts
  backend/src/modules/auth/index.ts
  backend/src/modules/index.ts
  backend/src/modules/matches/index.ts
  backend/src/modules/messages/index.ts
  backend/src/modules/users/index.ts
  backend/src/tsconfig.json
Labels: enhancement

#19 Integration on the AI component
  backend/bun.lock
  backend/package-lock.json
  backend/package.json
  backend/src/modules/ai/translation.service.ts
  backend/src/modules/ai/translation.ts
  backend/src/modules/messages/index.ts
  frontend/bun.lock
  frontend/package.json
Labels: enhancement

#21 Created `LICENSE.md` file for Love-Language-GPT
  LICENSE
  README.md
Labels: documentation, help wanted

#23 Website Assets
  frontend/src/assets/Default_PFP.png
  frontend/src/assets/LLGPT_Logo_Horizontal.png
  frontend/src/assets/LLGPT_Logo_Vertical.png
  frontend/src/assets/gama-films-cWeRjegaVLg-unsplash.jpg
  frontend/src/assets/joyce-busola-dwmhtK_zX6Y-unsplash.jpg
  frontend/src/assets/maccy-HvIrf_slw4Q-unsplash.jpg
  frontend/src/assets/michael-martinelli--CPRUDsU7Mo-unsplash.jpg
  frontend/src/assets/ph-m-tr-n-hoan-th-nh-nzKj7DEYKAA-unsplash.jpg
  frontend/src/assets/sincerely-media-F466AcbeILI-unsplash.jpg
  frontend/src/components/Parentcont/index.tsx
  frontend/src/components/Redirbtn/index.tsx
  frontend/src/routes/about/index.tsx
  frontend/src/routes/ai/index.tsx
  frontend/src/routes/datefinder/index.tsx
  frontend/src/routes/dictionary/index.tsx
  frontend/src/routes/home/index.tsx
  frontend/src/routes/index.tsx
Labels: enhancement

#24 Connect backend with frontend
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/services/ai.ts
  backend/src/ws.ts
  frontend/src/integrations/api.ts
  frontend/tsconfig.json
Labels: documentation

#25 Website Styling
  frontend/src/components/Parentcont/index.tsx
  frontend/src/routes/about/index.tsx
  frontend/src/routes/ai/index.tsx
  frontend/src/routes/home/index.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/privacypolicy/index.tsx
  frontend/src/routes/termsofservice/index.tsx
Labels: enhancement
